name: Deploy HTML App

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: windows-latest

    env:
      webAppName: testappazlab
      resourceGroup: azlab
      packagePath: ${{ github.workspace }}\webapp.zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Prepare HTML content
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path "${{ github.workspace }}\webapp" -Force
        Copy-Item -Path "${{ github.workspace }}\index*.html" -Destination "${{ github.workspace }}\webapp" -Force
        Copy-Item -Path "${{ github.workspace }}\web.config" -Destination "${{ github.workspace }}\webapp" -Force
        Compress-Archive -Path "${{ github.workspace }}\webapp\*" -DestinationPath "${{ env.packagePath }}" -Force

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop
        path: ${{ env.packagePath }}

