name: Deploy HTML App

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: windows-latest

    env:
      webAppName: testappazlab
      resourceGroup: azlab
      packagePath: ${{ github.workspace }}\webapp.zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Prepare HTML content
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path "${{ github.workspace }}\webapp" -Force
        Copy-Item -Path "${{ github.workspace }}\index*.html" -Destination "${{ github.workspace }}\webapp" -Force
        Copy-Item -Path "${{ github.workspace }}\web.config" -Destination "${{ github.workspace }}\webapp" -Force
        Compress-Archive -Path "${{ github.workspace }}\webapp\*" -DestinationPath "${{ env.packagePath }}" -Force

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop
        path: ${{ env.packagePath }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.webAppName }}
        slot-name: production
        resource-group-name: ${{ env.resourceGroup }}
        package: ${{ env.packagePath }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
